"""empty message

Revision ID: 380b390d9a91
Revises: 60b0fd81138b
Create Date: 2020-03-31 16:44:07.055498

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '380b390d9a91'
down_revision = '60b0fd81138b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shop_cart', 'subTotal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shop_cart', sa.Column('subTotal', mysql.FLOAT(), nullable=True))
    # ### end Alembic commands ###
