"""empty message

Revision ID: 60b0fd81138b
Revises: 1548d804e208
Create Date: 2020-03-31 14:10:51.509161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60b0fd81138b'
down_revision = '1548d804e208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('comment_ibfk_1', 'comment', type_='foreignkey')
    op.drop_column('comment', 'comment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comment_ibfk_1', 'comment', 'comment', ['comment_id'], ['id'])
    # ### end Alembic commands ###
