"""empty message

Revision ID: c12f01c19613
Revises: 380b390d9a91
Create Date: 2020-04-02 15:23:16.894801

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c12f01c19613'
down_revision = '380b390d9a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('count', sa.Integer(), nullable=True))
    op.add_column('order', sa.Column('gid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order', 'goods', ['gid'], ['id'])
    op.drop_column('order', 'phone')
    op.drop_column('order', 'addr')
    op.drop_column('order', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('name', mysql.VARCHAR(length=50), nullable=False))
    op.add_column('order', sa.Column('addr', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('order', sa.Column('phone', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'gid')
    op.drop_column('order', 'count')
    # ### end Alembic commands ###
