"""empty message

Revision ID: f8a2cbed9c36
Revises: c12f01c19613
Create Date: 2020-04-03 10:11:30.309424

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f8a2cbed9c36'
down_revision = 'c12f01c19613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'order_last_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_last_time', mysql.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
